name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository with Submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive  # Ensure that submodules are fetched

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install

    - name: Build and Test
      run: |
        npm run build
        npm test

  publish-to-docker-hub:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    steps:
    - name: Checkout Repository with Submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive  # Ensure that submodules are fetched

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/server:latest -t ${{ secrets.DOCKER_HUB_USERNAME }}/server:${{ github.sha }} .

    - name: Logout from Docker Hub
      run: docker logout
